[webui]
shutdown = true

[log]
to_file = true
to_console = false

[backends.delayed_sonarr]
type = "Sonarr"
apikey = "delaysonkey"

[backends.delayed_lidarr]
type = "lIdarr"
apikey = "delaylidkey"

[backends.delayed_radarr]
type = "raDarr"
apikey = "delayradkey"

[trackers.delay]
irc_nickname = "bipbopdelayed"
irc_server = "test-url"
irc_port = 6667
irc_channels = "#delay"

announce_delay = 8
