[webui]
shutdown = true

[log]
to_file = true
to_console = false

[sonarr]
apikey = "delaysonkey"

[lidarr]
apikey = "delaylidkey"

[radarr]
apikey = "delayradkey"

[delay]
irc_nickname = "bipbopdelayed"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#delay"

announce_delay = 8
