[webui]
shutdown = true

[log]
to_file = true
to_console = false

[backends.line_sonarr]
type = "sonarr"
apikey = "lineapison"

[backends.line_lidarr]
type = "lidarr"
apikey = "lineapilid"

[backends.line_radarr]
type = "radarr"
apikey = "lineapirad"

[trackers.linematched]
irc_nickname = "linematcherbot"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#linematched"

[trackers.linematched.settings]
fixed1 = "mfix1&"
fixed2 = "mfix2&"
