[webui]
shutdown = true

[log]
to_file = true
to_console = false

[sonarr]
apikey = "lineapison"

[lidarr]
apikey = "lineapilid"

[radarr]
apikey = "lineapirad"

[trackers.linematched]
irc_nickname = "linematcherbot"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#linematched"

[trackers.linematched.settings]
fixed2 = "mfix2&"
