[webui]
shutdown = true

[log]
to_file = true
to_console = false

[backends.MySonarr]
type = "sonarr"
apikey = "sonapikey1"

[trackers.simple1]
irc_nickname = "bipbopmodes"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#simple1"
