[webui]
shutdown = true

[log]
to_file = true
to_console = false

[backends.my_sonarr]
type = "sonarr"
apikey = "abcdef123"

[backends.my_lidarr]
type = "lidarr"
apikey = "123456789"

[backends.my_radarr]
type = "radarr"
apikey = "987654321"

[trackers.multi]
irc_nickname = "bipbopimalsobot"
irc_server = "192.168.1.103"
irc_port = 6667
irc_channels = "#multi"
torrent_https = true

[trackers.multi.settings]
from_config = "cfgstr"
