[webui]
host = "0.0.0.0"
port = 3467
shutdown = true

[log]
to_file = true
to_console = false

[sonarr]
apikey = "abcdef123"

[radarr]
apikey = "987654321"

[single]
irc_nickname = "bipbopiambot"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#single"
fixed1 = "first_fixed"
fixed2 = "fixed_second"
notify_sonarr = true
