[webui]
shutdown = true

[log]
to_file = true
to_console = false

[sonarr]
apikey = "simplesonkey"

[lidarr]
apikey = "simplelidkey"

[radarr]
apikey = "simpleradkey"

[simple1]
irc_nickname = "bipbopsimple1"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#simple1"

[simple2]
irc_nickname = "bipbopsimple2"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#simple2"

[simple3]
irc_nickname = "bipbopsimple3"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#simple3"
