[webui]
host = "0.0.0.0"
port = 3467
username = "admin"
password = "password"
shutdown = "true"

[log]
to_file = true
to_console = false

[sonarr]
apikey = "abcdef123"

[lidarr]
apikey = "123456789"

[radarr]
apikey = "987654321"

[trackers.single]
irc_nickname = "bipbopiambot"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#single"

[trackers.single.settings]
fixed1 = "first_fixed"
fixed2 = "fixed_second"

[trackers.multi]
irc_nickname = "bipbopimalsobot"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#multi"
category_sonarr = "color"
category_radarr = "fruit"
category_lidarr = "tree|bush"

[trackers.multi.settings]
from_config = "config_string"
