[webui]
shutdown = true

[log]
to_file = true
to_console = false

[backends.my_sonarr]
type = "sonarr"
apikey = "simplesonkey"

[backends.my_lidarr]
type = "lidarr"
apikey = "simplelidkey"

[backends.my_radarr]
type = "radarr"
apikey = "simpleradkey"

[trackers.simple1]
irc_nickname = "bipbopstatus1"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#simple1"

[trackers.simple2]
irc_nickname = "bipbopstatus2"
irc_server = "192.168.1.10"
irc_port = 6667
irc_channels = "#simple2"

[trackers.simple3]
irc_nickname = "bipbopstatus3"
irc_server = "192.168.1.10"
irc_port = 6697
irc_channels = "#simple3"
irc_tls = true
